global:
  input_module: "Console"
  kernel_module: "CoreKernel"
  debug: "False"

kernel:
  daemonise: "False"

log:
  log_path: "<root_dir>/var/log/flint.log"
  log_level: "WARNING"

input:
  enabled_modules: "Console"

output:
  enabled_modules: "Console"

source:
  enabled_modules: "AlphaVantage"