global:
  input_module: "Console"
  kernel_module: "CoreKernel"
  debug: "False"
  exit_permitted_modules: {
    Console: True,
  }

kernel:
  daemonise: "False"

log:
  log_path: "<root_dir>/var/log/flint.log"
  log_level: "WARNING"

input:
  enabled_modules: "Console"

output:
  enabled_modules: "Console"

source:
  enabled_modules: "AlphaVantage"

cache:
  cache_method: "sqlite3"
  # For infinite lifespan set to 0
  cache_lifespan: 0

